name: Labeler-Release
on:
  pull_request:
    # branches:
    #   - main
    #   - master
    #   - staging
jobs:
  label:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'main') 
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/labeler-release.yml"